### ISSUE TITLE
Cannot build clustergen voice

### ISSUE THREAD

**Issue by MaheshVelankar** [festvox/festvox#1]
I tried to follow the steps to create clustergen voice.
However the sequence is failing to generate voice.

The script 
./bin/build_cg_rfs_voice
invokes the script
./bin/build_cg_voice

This script invokes the following line
./bin/do_clustergen dur etc/txt.done.data.train

Everything goes fine upto that line however

I start getting errors like
Cannot open file festival/utts_hmm/arctic_a0050.utt as tokenstream
load_utt: can't open utterance input file festival/utts_hmm/arctic_a0050.utt
utt.load: loading from "festival/utts_hmm/arctic_a0050.utt" failed
Cannot open file festival/utts_hmm/arctic_a0048.utt as tokenstream
load_utt: can't open utterance input file festival/utts_hmm/arctic_a0048.utt

etc

I looked into what is being done by above line. It invokes ./bin/do_clustergen. That has following snippet

if [ $1 = "dur" ]
then
   ./bin/make_dur_model_mcep $PROMPTFILE
   cp -p festvox/$FV_VOICENAME"_dur.scm" festvox/$FV_VOICENAME"_durdata_cg.scm"
   exit 0
fi
........the above snippet invokes ./bin/make_dur_model_mcep. It has following logic.
...
awk '{printf("festival/utts_hmm/%s.utt\n",$2)}' >utthmmfile
...

however the folder festival/utts_hmm is not populated at all at the time the above code is invoked.
.... and thus the errors start.

Further down the line .........it appears to go through an infinite loop.........not sure  about this.

Please let me know if I am following any wrong sequence of steps.
Please direct me to proper source where I can get any guideline, if you are busy.

Thanks in advance.
-Mahesh

**Comment by saikrishnarallabandi** [comment]
Hi,

Sorry for the delay in response. It seems that one of the earlier steps failed. Can you use the following commands (you can place them in a script) to see all the previous steps were executed correctly? Alternatively, you can paste a log file and I can inspect them.


./bin/do_build build_prompts etc/txt.done.data
./bin/do_build label etc/txt.done.data
./bin/do_clustergen parallel build_utts etc/txt.done.data
./bin/do_clustergen generate_statenames
./bin/do_clustergen generate_filters

./bin/do_clustergen parallel f0_v_sptk
./bin/do_clustergen parallel mcep_sptk
./bin/do_clustergen parallel combine_coeffs_v
./bin/traintest etc/txt.done.data
./bin/do_clustergen parallel cluster etc/txt.done.data.train
./bin/do_clustergen dur etc/txt.done.data.train

**Comment by saikrishnarallabandi** [comment]
closing for now. reopen if the problem persists

**Comment by shashankrnr32** [comment]
I am able to run till `./bin/traintest etc/txt.done.data`
When I run`./bin/do_clustergen parallel cluster etc/txt.done.data.train`, I get the following error. 
![screenshot from 2019-02-01 21-34-00](https://user-images.githubusercontent.com/29425899/52135861-cd0cc380-266c-11e9-859e-42b9f7b11032.png)

I have traced down the errors to do_clustergen and clustergen_build.scm. In one of the lines, the script loads from `festival/disttabs/unittypes` but the directory `festival/disttabs/` is empty. I dont think I have missed any steps. 
I am currently running Festvox 2.8 and Festival 2.5 and I have followed the steps given in the Website.
If you can find out what may have went wrong, do help me.

**Comment by ddavout** [comment]
the directory festival/disttabs get emptied anyway , the files are quite big ..
have you enough resources ? may each parallel process are killed by ubuntu silenciously 
just an idea ...

**Comment by shashankrnr32** [comment]
> the directory festival/disttabs get emptied anyway , the files are quite big ..
> have you enough resources ? may each parallel process are killed by ubuntu silenciously
> just an idea ...

Ya. Maybe this was the problem. I restarted the system(Unintentionally) and the thing worked. Maybe a lot of CPU resource is needed. 
But I am stuck at testing, where I am getting most of the testing audio are filled with noise and here and there I am able to recognize the speech. I trained with 700 Audio files . Is it enough? or anywhere I need to change my approach?

**Comment by ddavout** [comment]
the files generated by  the script can be huge more than 2 Go and the work is intense, I could not get to the end of clunits build before installing  swapspace that adapts virtual memory to the needs AND claim disk space to use as swap space (hence it's name).
for my clunits I use until now 3500 prompts or so: the output is  very good, it is was not the case for a clustergen; 700 may be not enough to obtain a satisfactory result but in my mind if every was ok you should not obtain "noise" .. I am going to listen to your sample wav

**Comment by saikrishnarallabandi** [comment]
closing
