### ISSUE TITLE
typo INST_LANG_VOX_other.scm

### ISSUE THREAD

**Issue by ddavout** [festvox/festvox#10]
https://github.com/festvox/festvox/blob/ec3e8b4ee739447b7c2a062506759049d4ab1b5a/src/vox_files/indic/INST_LANG_VOX_other.scm#L48-L52
should be (INST_LANG_VOX::reset_other), I presume

as in
  "(INST_LANG_VOX::select_other)
Set up the anything esle for the voice."
https://github.com/festvox/festvox/blob/ec3e8b4ee739447b7c2a062506759049d4ab1b5a/src/vox_files/general/INST_LANG_VOX_other.scm#L41

 +( typo  esle -> else )

**Comment by saikrishnarallabandi** [comment]
Thanks.

Corrected typo. Left the other setting as is for now since its configurable

https://github.com/festvox/festvox/commit/666efa570f7930678097f3f378962ca99179081f
