### ISSUE TITLE
pitch output format in festvox/src/clustergen/get_str_sptk

### ISSUE THREAD

**Issue by ddavout** [festvox/festvox#16]
in the doc, there is no output format "5" : only 0 for pitch, 1 for f0, 2 for log(f0) 
 pitch - pitch extraction
  usage:
       pitch [ options ] [ infile ] > stdout
  options:
       -a a  : algorithm used for pitch        [0]
               estimation
                 0 (RAPT)
                 1 (SWIPE')
       -s s  : sampling frequency (kHz)        [16.0]
       -p p  : frame shift                     [80]
       -T T  : voiced/unvoiced threshold       [0.0]
               (used only for RAPT algorithm)
       -t t  : voiced/unvoiced threshold       [0.3]
               (used only for SWIPE' algorithm)
       -L L  : minimum fundamental             [60]
               frequency to search for (Hz)
       -H H  : maximum fundamental             [240]
               frequency to search for (Hz)
       -o o  : output format                   [0]
                 0 (pitch)
                 1 (f0)
                 2 (log(f0))

```
 for i in `seq 1 5`
    do
	$ESTDIR/bin/sigfilter -firfilter $FTMP.h$i -forder $FORDER wav/$fname.wav -otype raw | \
	    $X2X +sf | $SPTKDIR/bin/pitch -a 0 -H $F0MAX -L $F0MIN -p $FRAMESHIFT -s $SAMPKHZ -o 5 | \
	    $X2X +fa4 | awk '{print $4}' > $TMP.h$i.str
    done
```

luckily ifor swipe (SPTK-3.6/bin/pitch/swipe/swipe.c ) the default is :     /* pitch */
 but **what about rapt** ?  (pitch -a 0 )

**Comment by ddavout** [comment]
does it correspond to a new usage  ?
the expected result is found only for o 5 
o 1 : 40
o 2 : 40
o 0 : 40
o 5 : 160

**Comment by Shallowmallow** [comment]
in th SPTK Patch you can see

festvox is adding a new case
```
       switch (otype) {
-      case 1:                   /* f0 */
+        case 1:                   /* f0 */
           fwrite(tmp + i, sizeof(float), 1, stdout);
           break;
-      case 2:                   /* log(f0) */
+        case 2:                   /* log(f0) */
           if (tmp[i] != 0.0) {
-              tmp[i] = log(tmp[i]);
+            tmp[i] = log(tmp[i]);
           } else {
-              tmp[i] = -1.0E10;
+            tmp[i] = -1.0E10;
           }
           fwrite(tmp + i, sizeof(float), 1, stdout);
           break;
-      default:                  /* pitch */
+        case 5:                   /* f0, voicing and acpeak */
+          fwrite(tmp + i, sizeof(float), 1, stdout);
+          fwrite(unvoiced + i, sizeof(float), 1, stdout);
+          fwrite(rmse + i, sizeof(float), 1, stdout);
+          fwrite(acpeak + i, sizeof(float), 1, stdout);
+          break;
```
