### ISSUE TITLE
help needed  for 44100 Hz : mcep

### ISSUE THREAD

**Issue by ddavout** [festvox/festvox#18]
https://github.com/festvox/festvox/blob/ec3e8b4ee739447b7c2a062506759049d4ab1b5a/src/unitsel/make_mcep#L51-L53

https://github.com/festvox/festvox/blob/ec3e8b4ee739447b7c2a062506759049d4ab1b5a/src/general/make_labs#L65-L68
Could it be that these parameters are not "reasonable"
for a voice in 44100 Hz?
I certainly not know  better, and I desperately need help.
Thanks for any light

**Comment by saikrishnarallabandi** [comment]
Sorry for the delay in response. The new script supports 44K 

https://github.com/festvox/festvox/blob/f49c3dab3f0473cf04c7752f22305583e22d859b/src/clustergen/do_clustergen#L519

Lmk if this helps

**Comment by saikrishnarallabandi** [comment]
closing. reopen if necessary
