### ISSUE TITLE
Unable to build festvox on my system(ubuntu 18.04)

### ISSUE THREAD

**Issue by deep4U** [festvox/festvox#2]
Please find the logs attached
festvox does not build in my system
Please find ./configure and make logs below.

[conf_log.txt](https://github.com/festvox/festvox/files/2160472/conf_log.txt)
[make_log.txt](https://github.com/festvox/festvox/files/2160473/make_log.txt)

**Comment by saikrishnarallabandi** [comment]
Hi. 

mm. I dont seem to find any error in the logs. 

Have you attached the full logs?

**Comment by deep4U** [comment]
if you would be kind enough to search for the word error in make_log.txt after pressing ctrl+f you'd see alot of them ....
just an example would be 

smooth_f0_main.cc:142:15: error: ‘class EST_Relation’ has no member named ‘rlast’; did you mean ‘last’?
        if (r->rlast()->F("end") > f0_in.end())
               ^~~~~
               last
smooth_f0_main.cc:146:25: error: ‘class EST_Relation’ has no member named ‘rlast’; did you mean ‘last’?
         (int)(cn-1+((r->rlast()->F("end")-f0_in.end())/f0_in.shift())),
                         ^~~~~
                         last
smooth_f0_main.cc:156:10: error: ‘class EST_Relation’ has no member named ‘rlast’; did you mean ‘last’?
  if ((r->rlast() == 0) ||
          ^~~~~
          last
smooth_f0_main.cc:157:10: error: ‘class EST_Relation’ has no member named ‘rlast’; did you mean ‘last’?
      (r->rlast()->F("end") < f0_in.end()))
          ^~~~~
          last
smooth_f0_main.cc:170:10: error: ‘inext’ was not declared in this scope
   item = inext(item);
          ^~~~~
smooth_f0_main.cc:170:10: note: suggested alternative: ‘invert’
   item = inext(item);
          ^~~~~
          invert
Makefile:95: recipe for target 'smooth_f0_main.o' failed
make[2]: *** [smooth_f0_main.o] Error 1
making in src/diphones ...


starting at line 91 of make_log.txt

**Comment by ddavout** [comment]
and what about this one ? 
**/usr/bin/x86_64-linux-gnu-ld: cannot find -lsub**

gmm_sub.cc:1032:46: note: in expansion of macro ‘NUL’
     if ((ofp = fopen(gammamatfile, "wb")) == NUL) {
                                              ^~~
Makefile:60: recipe for target 'gmm_sub.o' failed
make[4]: *** [gmm_sub.o] Error 1
making in src/vc/src/analysis ...
g++   -g -O2 -Wall -c main.cc -o main.o
g++   -g -O2 -Wall -c analysis_sub.cc -o analysis_sub.o
g++ -o analysis main.o analysis_sub.o -L../lib -lsub -lsp
/usr/bin/x86_64-linux-gnu-ld: cannot find -lsub
collect2: error: ld returned 1 exit status
Makefile:65: recipe for target 'analysis' failed
make[4]: *** [analysis] Error 1
making in src/vc/src/extdim ...
g++   -g -O2 -Wall -c main.cc -o main.o
main.cc: In function ‘int main(int, char**)’:
main.cc:193:10: warning: suggest explicit braces to avoid ambiguous ‘else’ [-Wdangling-else]
       if (chiv->data[l] != 0.0)
          ^
g++ -o extdim main.o -L../lib -lsub -lsp
/usr/bin/x86_64-linux-gnu-ld: cannot find -lsub
collect2: error: ld returned 1 exit status
Makefile:65: recipe for target 'extdim' failed

**Comment by Shallowmallow** [comment]
I have the same problem on Ubuntu 18.04   "/usr/bin/x86_64-linux-gnu-ld: cannot find -lsub"

**Comment by shashankrnr32** [comment]
> I have the same problem on Ubuntu 18.04 "/usr/bin/x86_64-linux-gnu-ld: cannot find -lsub"
> 
> Edit: ` ./configure CXX=g++-4.8 CC=gcc-4.8 CFLAGS=-fpermissive` before making it seems to work

This was the one i was looking for. Thank you

**Comment by saikrishnarallabandi** [comment]
closing
