### ISSUE TITLE
Error when building prompts

### ISSUE THREAD

**Issue by priyanthini** [festvox/festvox#21]
I'm tring to build Tamil voice . I have followed all the steps mentioned in " https://github.com/festvox/festvox/blob/master/docbook/grapheme.sgml ". But when I'm trying to build prompts error comes as " **ta_1871 PROMPTS
LEXICON: Word நீண்ட (plus features) not found in lexicon** " for almost all the words.
But all those words are in the lexicon. 
Why is that error coming ?

**Comment by ddavout** [comment]
a bare grapheme voice ? you have a more specialized tool
https://www.parlikar.com/files/aup_wildre_2016.pdf
