### ISSUE TITLE
spelling of a variable EXPERMIENT / EXPERIMENT

### ISSUE THREAD

**Issue by ddavout** [festvox/festvox#22]
https://github.com/festvox/festvox/blob/ec3e8b4ee739447b7c2a062506759049d4ab1b5a/src/clustergen/cg_test#L172

**Comment by saikrishnarallabandi** [comment]
Corrected. Thanks

https://github.com/festvox/festvox/commit/f49c3dab3f0473cf04c7752f22305583e22d859b
