### ISSUE TITLE
Error in building prompts

### ISSUE THREAD

**Issue by priyanthini** [festvox/festvox#25]
Hi, I'm getting the following error when trying to build prompts.

free(): invalid next size (fast)
Aborted (core dumped)

Can someone tell me the reason and solution for this please.

Thank you

**Comment by saikrishnarallabandi** [comment]
looks like memory issue. 
are there super long prompts in the dataset?

The heapsize can be manually increased by changing this line
https://github.com/festvox/festvox/blob/d443c330a4e82c8d9cdf5bac57ad4668e3fc7d40/src/general/do_build#L67

**Comment by priyanthini** [comment]
I don't think like there are super long prompts. By the way, how much should I assign to the HEAPSIZE to fix the issue?

**Comment by festvox** [comment]
Its not clear its the number of prompts or the size of HEAPSIZE, it might
be the amount of memory on your machine (or virtual machine).  You probably
want to have at least 2G per thread on your machine.  Also make sure
you don't have some other process using up all the memory.  I'm not sure if
that's the problem, but the error looks like not enough memory (or corrupt
memory).

This should be big enough for most voices.
export SIODHEAPSIZE=20000000

Alan

**Comment by priyanthini** [comment]
Okay I will check the memory and do it again.

**Comment by priyanthini** [comment]
Hi,
This error came as a result of lack of memory. I solved this by building this festival tts on a server machine than building it on my machine.
So I'm closing this error now.

Thank you
