### ISSUE TITLE
Unable to build voice for non-English language (Bengali)

### ISSUE THREAD

**Issue by numan947** [festvox/festvox#3]
I followed the steps mentioned in [Building Indic voices](http://festvox.org/bsv/x3528.html) and [another issue's comment](https://github.com/festvox/festvox/issues/1#issuecomment-370221574) and tried to build voice for Bengali language, but failed to do so. What I did is given below:

- 1. I downloaded the data available in [Fesvox's example Indic database](http://festvox.org/h2r_indic/). I used only a small portion of it (20 files) for the process, as training took long time in the first try.

- 2. I installed SPTK-3.6,festvox2.4, festival2.4, speech-tools2.4 in a directory, installed them (without error) and configured FESTVOXDIR, ESTDIR, SPTKDIR environment variables (in Ubuntu 16.04).

- 3. I installed SPTK-3.6,festvox2.5, festival2.5, speech-tools2.5 in a directory, installed them (without error) and configured FESTVOXDIR, ESTDIR, SPTKDIR environment variables (in Ubuntu 16.04).

- 4. I followed the instructions given in the link [Building Indic voices](http://festvox.org/bsv/x3528.html), as well as from [another issue's comment](https://github.com/festvox/festvox/issues/1#issuecomment-370221574)  for both version-2.4 and version-2.5 (I know about the change in these version about setting `(defvar lex:language 'Hindi)` to `Bengali` and set them accordingly).
- 5. When building with festvox2.4 and other 2.4-releases, I didn't face problem during training, the whole process went smoothly. But when I ran the following lines mentioned in [Building Indic voices](http://festvox.org/bsv/x3528.html), I get error.
>And generate some test examples, the first to give MCD and F0D objective measures, the second to generate standard tts output
`./bin/do_clustergen cg_test resynth cgp etc/txt.done.data.test`
`./bin/do_clustergen cg_test tts tts etc/txt.done.data.test`
Error I faced:
```
CG test_resynth bn_00010
SIOD ERROR: unbound variable : rfs_info
CG test_resynth bn_00010 Failed
CG test_resynth bn_00021 
Segmentation fault (core dumped)
awk: cmd. line:2: fatal: division by zero attempted
awk: cmd. line:2: fatal: division by zero attempted
awk: cmd. line:2: fatal: division by zero attempted
awk: cmd. line:2: fatal: division by zero attempted
```
- 5. When tried to build with festvox-2.5 and other 2.5-releases from this github account, I faced error, after the following command mentioned in both of the sources ([another issue's comment](https://github.com/festvox/festvox/issues/1#issuecomment-370221574)  and [Building Indic voices](http://festvox.org/bsv/x3528.html) ). The command is:
`./bin/do_clustergen parallel cluster etc/txt.done.data.train`
and the error I found:
```
Setting clustergen params
SIOD ERROR: unbound variable : cg:f0_clustersize
BACKTRACE:
   0: cg:f0_clustersize
   1: (list (quote wagon_cluster_size_f0) cg:f0_clustersize)
   2: (list
    (quote (clunit_relation mcep))
    (list (quote wagon_cluster_size_mcep) cg:mcep_clustersize)
    ...)
   3: (append
    (list
     (quote (clunit_relation mcep))
     (list (quote wagon_cluster_size_mcep) cg:mcep_clustersize)
     ...)
    clunits_params)
   4: (set!
    clustergen_params
    (append
     (...)
     clunits_params))
   5: (begin
    (set! cg:parallel_tree_build t)
    (build_clustergen "etc/txt.done.data.train"))
```
Please let me know, if I am doing something wrong, and if possible, direct me to the correct steps. If possible, direct me to some proper sources that I can use to build Indic voices in Festival/Festvox.

Thanks,
~Numan

**Comment by saikrishnarallabandi** [comment]
Hey so sorry. didnt notice this. Are you still with this?

**Comment by saikrishnarallabandi** [comment]
This is due to some error in the Random Forest build process. Rebuilding should mostly solve.

Closing this. Please reopen if the issue still persists.
