### ISSUE TITLE
SIOD ERROR: null-arg-to-last in Brazilian Portuguese voice construction used Grapheme-based Synthesizer.

### ISSUE THREAD

**Issue by Pallas1303** [festvox/festvox#33]
Hello, I'm building a voice in Brazilian Portuguese used "Grapheme-based in [Grapheme-based Synthesizer](http://www.festvox.org/festvox/c3485.html), but in generating some test examples occurred:

./bin/do_clustergen cg_test tts tts etc/txt.done.data.test Resulting in SIOD ERROR: null-arg-to-last.

The database has 600 audios on average from 3 to 8 seconds long. All training commands and generation of label the data and prompts. and feature extraction are successful.

**Comment by awbcmu** [comment]
There are a couple of things that could cause this, there may be a an error
earlier than caused an incomplete file to be created so it can't fully load
a model.  I would need to see the whole output at the time of error to
narrow that down.

Also it is possible your SIOD heap isn't big enough, this happens on
"large" rfs models, sometimes, you can make a bigger SIOD heap by (at the
command line level

export SIODHEAPSIZE=60000000

(sixty million), and try to increase from there.  Do check that you have
properly escaped double quotes in your txt.done.data file so it isn't
causing errors in that file itself.

Alan

**Comment by awbcmu** [comment]
You should remove the fileids from your txt.done.data if there are missing
.utt files (assuming its only a few).  They probably have misaligned for
some reasons, but they aren't helping the build.  If its a lots of files
that don't aligned, (check if there are .lab files for them in lab/*.lb)
then if might be a bigger problem.

Alan

**Comment by Pallas1303** [comment]
The txt file.date.done had characters with accents like "ã, à, õ" and after doing that in generation .train had several white spaces where it had the characters.

**Comment by Pallas1303** [comment]
I managed to solve the error, occurred by having insufficient audios and with very low quality to make the models.
I I will close this problem, thank you very much for the attention.
