### ISSUE TITLE
What are archives .frq generated in the process of voice construction?

### ISSUE THREAD

**Issue by Pallas1303** [festvox/festvox#34]
Hello, In building the voice model, I noticed that it has files called.frq what he are? Are files related to frequency and pitch and etc? I have a database that has some files .frq and files .llsm, is it possible to utilize it these files in the database for voice construction?

**Comment by awbcmu** [comment]
What type of voice are you building?  I've don't see .frq or .llsm in my
builds.

Alan

**Comment by Pallas1303** [comment]
Sorry, I had mistaken myself, I was using a database of transcribed audios accompanied with these files. I'm really sorry.
