### ISSUE TITLE
no make_dur_model when using setup_clunits

### ISSUE THREAD

**Issue by rayw0ng** [festvox/festvox#5]
When using `setup_clunits` to setup a voice project, there is no `make_dur_model` under folder `bin`, but `build_clunits_voice` need `make_dur_model` under folder `bin`.

**Comment by ddavout** [comment]
this the job of setup_prosody

echo Copying intonation files
cp -p $FESTVOXDIR/src/intonation/make_f0_pm bin
cp -p $FESTVOXDIR/src/intonation/make_f0_pm_get_f0 bin
cp -p $FESTVOXDIR/src/intonation/find_f0_stats bin
cp -p $FESTVOXDIR/src/intonation/make_f0_model bin
cp -p $FESTVOXDIR/src/intonation/make_f0_v_sptk bin
cp -p $FESTVOXDIR/src/intonation/make_f0_v_world bin
cp -p $FESTVOXDIR/src/intonation/f0.feats festival/f0/etc
cp -p $FESTVOXDIR/src/intonation/tree_f0.scm festvox

echo Copying duration files
cp -p $FESTVOXDIR/src/duration/make_dur_model bin
cp -p $FESTVOXDIR/src/duration/logdurn.scm festival/dur/etc
cp -p $FESTVOXDIR/src/duration/dur.feats festival/dur/etc

echo "Set up for "$FV_VOICENAME" prosody complete"

2018-08-30 16:06 UTC, rayw0ng <notifications@github.com>:

**Comment by rayw0ng** [comment]
Got it. Thanks.
