### ISSUE TITLE
How to integrate my build voice with festival 

### ISSUE THREAD

**Issue by skmalviya** [festvox/festvox#6]
I have already build some indic tts models using festvox, I want to integrate them into festival so that i can play the utterance from command line. Like:
festival '(SayText "नमस्कार आपका स्वागत है.")'.

**Comment by saikrishnarallabandi** [comment]
so sorry cudnt get to this earlier. Are u still facing the issue? 

one line answer: placing the vox files in festival/lib should do the trick. Please get back to me if you need further details.
